import Link from "next/link";
import Image from "next/image";
import { categories, categoryImage, products, bannerBlur } from "@/lib/data";
import { ProductCard, Icon } from "@/components/Ui";
export default function Home() { return <div className="home">
  <section className="hero"><Image src="/banner.webp" alt="A selection of Hasn Al Wadi spices" fill priority sizes="100vw" placeholder="blur" blurDataURL={bannerBlur} className="object-cover"/><div className="hero-shade"/><div className="hero-content"><p className="hero-kicker">Hasn Al Wadi Flour Mill</p><h1>Good ingredients make every meal feel like home.</h1><p>Quality pantry staples, carefully selected and packed for your kitchen.</p><div className="hero-buttons"><Link href="/products" className="btn btn-primary">Shop the collection <Icon name="arrow" size={16}/></Link><Link href="/contact" className="btn hero-secondary">Talk to our team</Link></div></div><div className="hero-caption">Established in Umm Al Quwain<br/>Serving kitchens across the UAE</div></section>
  <section className="home-section intro"><p className="eyebrow">Made for everyday cooking</p><div><h2>A well-stocked pantry starts here.</h2><p>From fragrant whole spices to dependable rice and pulses, find the ingredients your family reaches for every day.</p></div></section>
  <section id="categories" className="home-section"><div className="section-heading"><div><p className="eyebrow">Browse by need</p><h2>Shop the pantry</h2></div><Link href="/products" className="text-link">View all products <Icon name="arrow" size={15}/></Link></div><div className="category-grid">{categories.map(c => <Link key={c.id} href={`/products?cat=${c.slug}`} className="category-card"><Image src={categoryImage(c.id)} alt="" fill sizes="(max-width:700px) 50vw, 25vw" className="object-cover"/><span/><div><p>{c.name}</p><small>{c.description}</small></div></Link>)}</div></section>
  <section className="home-section"><div className="section-heading"><div><p className="eyebrow">Popular picks</p><h2>Start with the essentials</h2></div><Link href="/products" className="text-link">Shop all <Icon name="arrow" size={15}/></Link></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-5">{products.filter(p => p.featured).map((p,i) => <ProductCard key={p.id} p={p} priority={i < 2}/>)}</div></section>
  <section className="promise"><div><p className="eyebrow">The Hasn Al Wadi standard</p><h2>Simply good food, chosen with care.</h2><p>We bring dependable quality to the staples behind your favourite family recipes.</p></div><div className="promise-list"><div><b>01</b><span><strong>Selected quality</strong><small>Ingredients you can trust</small></span></div><div><b>02</b><span><strong>Easy ordering</strong><small>Send your order on WhatsApp</small></span></div><div><b>03</b><span><strong>Local service</strong><small>From Umm Al Quwain, UAE</small></span></div></div></section>
  <section className="home-section order-steps"><p className="eyebrow">A straightforward order</p><h2>From shelf to your door in a few taps.</h2><div>{[["01","Choose your products"],["02","Add them to your basket"],["03","Share your details"],["04","Confirm on WhatsApp"]].map(([n,t])=><article key={n}><b>{n}</b><p>{t}</p></article>)}</div></section>
</div>; }
