"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useCart, useHydrated } from "@/lib/cart";
import { business } from "@/lib/config";
import Image from "next/image";
import { categories, fmt, type Product } from "@/lib/data";

type IconName = "search" | "bag" | "home" | "grid" | "receipt" | "phone" | "arrow" | "plus" | "minus" | "mail" | "check";
export function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, React.ReactNode> = {
    search: <><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></>, bag: <><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>, home: <><path d="m3 10 9-7 9 7v10H3V10Z"/><path d="M9 20v-6h6v6"/></>, grid: <><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>, receipt: <><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6"/></>, phone: <path d="M7 3h3l1.5 5-2.5 1.5a15 15 0 0 0 5.5 5.5L16 12.5 21 14v3c0 1.1-.9 2-2 2C10.2 19 5 13.8 5 5c0-1.1.9-2 2-2Z"/>, arrow: <><path d="M5 12h14"/><path d="m13 6 6 6-6 6"/></>, plus: <><path d="M12 5v14M5 12h14"/></>, minus: <path d="M5 12h14"/>, mail: <><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></>, check: <path d="m5 12 4 4L19 6"/>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
export function Qty({ p, v }: { p: string; v: string }) { const { items, addItem, increaseQuantity, decreaseQuantity } = useCart(); const h = useHydrated(); const q = h ? items.find((i) => i.productId === p && i.variantId === v)?.qty ?? 0 : 0; if (!q) return <button className="btn btn-primary w-full" onClick={() => addItem(p, v)}>Add to basket <Icon name="plus" size={16}/></button>; return <div className="quantity" role="group" aria-label="Quantity"><button aria-label="Decrease quantity" onClick={() => decreaseQuantity(p, v)}><Icon name="minus" size={16}/></button><span aria-live="polite">{q}</span><button aria-label="Increase quantity" onClick={() => increaseQuantity(p, v)}><Icon name="plus" size={16}/></button></div>; }
export function ProductCard({ p, priority = false }: { p: Product; priority?: boolean }) { const v = p.variants[0]; return <article className="product-card"><Link href={`/product/${p.slug}`} className="block group"><div className="product-image"><Image src={p.image} alt={`${p.name} pack`} fill sizes="(max-width:768px) 50vw, (max-width:1280px) 33vw, 25vw" placeholder="blur" blurDataURL={p.blur} priority={priority} className="object-cover transition-transform duration-500 group-hover:scale-105"/></div><div className="product-copy"><p className="eyebrow">{p.category}</p><h3>{p.name}</h3></div></Link><div className="product-actions"><p className={`product-price ${v.price == null ? "muted" : ""}`}>{fmt(v.price)}</p><Qty p={p.id} v={v.id}/></div></article>; }
export function Header() { const { items } = useCart(); const h = useHydrated(); const n = h ? items.reduce((a, i) => a + i.qty, 0) : 0; return <><div className="utility"><div className="shell"><span>Thoughtfully packed pantry essentials</span><span className="hidden sm:inline">Umm Al Quwain, UAE</span></div></div><header className="site-header"><div className="shell header-inner"><Link href="/" className="brand" aria-label="Hasn Al Wadi home"><img src={business.logo} alt="Hasn Al Wadi Elegant Quality"/></Link><nav className="desktop-nav" aria-label="Main">{[["/", "Home"], ["/products", "Shop"], ["/#categories", "Categories"], ["/contact", "Our story"]].map(([href, label]) => <Link key={href} href={href}>{label}</Link>)}</nav><div className="header-actions"><Link href="/products" aria-label="Search products" className="icon-button"><Icon name="search"/></Link><Link href="/cart" aria-label={`Basket, ${n} items`} className="icon-button relative"><Icon name="bag"/>{n > 0 && <span className="cart-count">{n}</span>}</Link></div></div></header></>; }
export function BottomNav() { const { items } = useCart(); const h = useHydrated(); const n = h ? items.reduce((a, i) => a + i.qty, 0) : 0; const path = usePathname(); const t: [string, IconName, string][] = [["/", "home", "Home"], ["/products", "grid", "Shop"], ["/cart", "bag", "Basket"], ["/orders", "receipt", "Orders"], ["/contact", "phone", "Contact"]]; return <nav aria-label="Mobile navigation" className="bottom-nav">{t.map(([href, ic, label]) => <Link key={href} href={href} className={path === href ? "active" : ""}><span className="relative"><Icon name={ic}/>{label === "Basket" && n > 0 && <i className="mobile-count">{n}</i>}</span><small>{label}</small></Link>)}</nav>; }
export function Footer() { return <footer className="footer"><div className="shell footer-grid"><div><div className="footer-brand">Hasn Al Wadi</div><p>Everyday ingredients selected for the meals that bring people together.</p></div><div><p className="footer-label">Explore</p><Link href="/products">All products</Link>{categories.map((c) => <Link key={c.id} href={`/products?cat=${c.slug}`}>{c.name}</Link>)}</div><div><p className="footer-label">Get in touch</p><p>{business.location}</p>{business.phoneNumbers.map((p) => <a key={p} href={`tel:${p}`}>{p}</a>)}<a href={`mailto:${business.email}`}>{business.email}</a></div></div><div className="shell footer-bottom">© {new Date().getFullYear()} {business.businessName}</div></footer>; }
export function Empty({ title, text, href, cta }: { title: string; text: string; href: string; cta: string }) { return <div className="empty-state"><div className="empty-icon"><Icon name="bag" size={28}/></div><h1>{title}</h1>{text && <p>{text}</p>}<Link href={href} className="btn btn-primary">{cta}<Icon name="arrow" size={16}/></Link></div>; }
