"use client";
import { Suspense, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { categories, products } from "@/lib/data";
import { ProductCard, Icon } from "@/components/Ui";

function List() {
  const sp = useSearchParams(); const [cat, setCat] = useState(sp.get("cat") ?? "all"); const [q, setQ] = useState(""); const [dq, setDq] = useState(""); const [sort, setSort] = useState("featured"); const [stock, setStock] = useState(false); const [open, setOpen] = useState(false);
  useEffect(() => { const t = setTimeout(() => setDq(q.trim().toLowerCase()), 150); return () => clearTimeout(t); }, [q]);
  const res = useMemo(() => { let r = products.filter(p => p.active && (cat === "all" || p.category === cat) && (!dq || [p.name, p.category, ...p.keywords].join(" ").toLowerCase().includes(dq)) && (!stock || p.variants.some(v => v.stockStatus === "IN_STOCK"))); if (sort === "name") r = [...r].sort((a,b) => a.name.localeCompare(b.name)); return r; }, [cat, dq, sort, stock]);
  const options = [{ slug: "all", name: "All products" }, ...categories];
  const filters = <div className="filter-content"><div className="filter-group"><p className="filter-label">Category</p><div className="filter-options">{options.map(c => <label key={c.slug} className={cat === c.slug ? "selected" : ""}><input type="radio" name="category" checked={cat === c.slug} onChange={() => setCat(c.slug)}/><span>{c.name}</span><small>{c.slug === "all" ? products.length : products.filter(p => p.category === c.slug).length}</small></label>)}</div></div><div className="filter-group"><p className="filter-label">Availability</p><label className="check-filter"><input type="checkbox" checked={stock} onChange={e => setStock(e.target.checked)}/><span>In stock only</span></label></div><div className="filter-group"><label className="filter-label" htmlFor="sort">Sort products</label><select id="sort" className="inp" value={sort} onChange={e => setSort(e.target.value)}><option value="featured">Featured first</option><option value="name">Name, A–Z</option></select></div></div>;
  return <div className="catalogue"><header className="catalogue-head"><p className="eyebrow">The collection</p><h1>Pantry essentials, selected with care.</h1><p>Explore quality rice, flour, pulses and spices for every kitchen.</p></header><div className="catalogue-tools"><label className="catalogue-search"><Icon name="search" size={19}/><input type="search" placeholder="Search products" aria-label="Search products" value={q} onChange={e => setQ(e.target.value)}/></label><button className="filter-trigger" onClick={() => setOpen(true)}>Filters <span>{cat === "all" && !stock ? "" : "•"}</span></button></div><div className="catalogue-layout"><aside className="catalogue-filter"><div className="filter-title"><span>Filter products</span><button onClick={() => {setCat("all");setStock(false)}}>Clear</button></div>{filters}</aside><section><div className="catalogue-result"><p><strong>{res.length}</strong> {res.length === 1 ? "product" : "products"}{cat !== "all" ? ` in ${options.find(o => o.slug === cat)?.name}` : ""}</p>{cat !== "all" && <button onClick={() => setCat("all")}>Clear filter ×</button>}</div>{res.length === 0 ? <div className="empty-state"><h1>No products found</h1><p>Try a different search or filter.</p><button className="btn btn-primary" onClick={() => {setCat("all");setQ("")}}>Show all products</button></div> : <div className="catalogue-grid">{res.map(p => <ProductCard key={p.id} p={p}/>)}</div>}</section></div>{open && <div className="filter-sheet-backdrop" onClick={() => setOpen(false)}><div className="filter-sheet" role="dialog" aria-modal="true" aria-label="Filter products" onClick={e => e.stopPropagation()}><div className="filter-sheet-head"><strong>Filter products</strong><button onClick={() => setOpen(false)} aria-label="Close filters">×</button></div>{filters}<button className="btn btn-primary w-full" onClick={() => setOpen(false)}>Show {res.length} products</button></div></div>}</div>;
}
export default function Page() { return <Suspense fallback={<p className="py-10 text-center">Loading products…</p>}><List/></Suspense>; }
